// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1BKtowrlUySB50gicmiFjhYA8rim5tfQ',
    appId: '1:350827354308:android:a7d7b8cd60a11fa59b5191',
    messagingSenderId: '350827354308',
    projectId: 'eticaret-f9fd9',
    storageBucket: 'eticaret-f9fd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuh-fhgbWP-mvb2LpIQxErQLjVNppsG_8',
    appId: '1:350827354308:ios:8101ee852919d66b9b5191',
    messagingSenderId: '350827354308',
    projectId: 'eticaret-f9fd9',
    storageBucket: 'eticaret-f9fd9.appspot.com',
    androidClientId: '350827354308-q00m5br2ifm77qfu9f6pus0sscs9cv35.apps.googleusercontent.com',
    iosClientId: '350827354308-oljbstnkhqm6r0qnvoekhda0k650m7ig.apps.googleusercontent.com',
    iosBundleId: 'com.mmt.ecommerceMobile',
  );
}
